
on:
  push: 
    branches: 
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME4 }} --password ${{ secrets.DOCKER_TOKEN }}



